# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f633a86bd9fb56e822ba7b4aaa85f1694c04741231540e63264ac7a1bb4198f972206d9e2f51c86301ddfaa95846fd40609bb4df5ef78c8660aba97f780fdc6a

test:
  secret_key_base: 6118deb007adbe3434b80a54398c14ccf0b3f182f3c437a10aaa0f5a8aea769d144742318999df6bf0e0ccb92b52cda0fa98b17cb738f2988e5eee71ccb25a55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
